## NumPy

https://numpy.org/

In [1]:
# Importando o NumPy
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [2]:
print(np.__version__)
np.set_printoptions(suppress=True)

1.26.4


### Criando Arrays NumPy

In [3]:
# Array criado a partir de uma lista Python
a = np.array([1, 2,3,4,5,6,7,8])
print(a)

[1 2 3 4 5 6 7 8]


In [4]:
#Podemos determinar o tipo de dado do array
b = np.array([1, 2,3,4,5,6,7,8], dtype=complex)
print(b)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j]


In [5]:
#Podemos definir o formato do array
c = np.array([1, 2,3,4,5,6,7,8]).reshape(2, 4)
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#Podemos transfomar uma matriz multidimensional em uma arry monodimensional
d = c.flatten()
print(d)

[1 2 3 4 5 6 7 8]


In [7]:
#Podemos criar arrays vazios
e= np.empty((3,3))
print(e)
#Cuidado com este comando, ele cria um espaço na memóeia, mas não limpa, o print vai mostra a sujeira

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Podemos cria arrays com um valor específico
f = np.full((4,6),99,dtype='float')
print(f)

[[99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99.]
 [99. 99. 99. 99. 99. 99.]]


# Criando arrays especiais

In [9]:
#Array de zeros
g = np.zeros((3,4))
print(g)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
#Array de um
h = np.ones((3,4))
print(h)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
#Array contendo uma progressão aritmética a partir de um intervalo - start, stop, step
i = np.arange(0, 100, 2).reshape(10,5)
print(g)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#Array multidimensiona quadratico com 1 na diagonal
h = np.eye(3)
print(i)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [13]:
#Array com os valores passados como parâmetro, formam uma diagonal
j = np.diag(np.array([1, 2, 3, 4]))
print(j)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [14]:
#Array com sequência de números igualmente espaçados dentro de um intervalo especificado.
k = np.linspace(0, 10)
l = np.linspace(0, 10, 15)
print(k)
print(l)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [15]:
#Array com ums sequência de números igualmente espaçados em escala logarítmica dentro de um intervalo especificado
m = np.logspace(0, 10, 15)
print(m)

[1.00000000e+00 5.17947468e+00 2.68269580e+01 1.38949549e+02
 7.19685673e+02 3.72759372e+03 1.93069773e+04 1.00000000e+05
 5.17947468e+05 2.68269580e+06 1.38949549e+07 7.19685673e+07
 3.72759372e+08 1.93069773e+09 1.00000000e+10]


In [16]:
#Podemos criar arrays com valores aleatórios entre 0 e 1
n = np.random.rand(3,3)
print(n)

[[0.2908839  0.28392545 0.72151851]
 [0.10982245 0.10151857 0.12997594]
 [0.78354499 0.79572385 0.90700677]]


In [17]:
#Podemos criar arrays com uma distribuição normal
o = np.random.randn(3,3)
print(o)

[[-0.10079681 -0.6425453  -1.68490186]
 [-0.85703074  0.77437711  0.17689879]
 [-1.73679114 -0.08924937  1.89282614]]


In [18]:
#Podemos criar arrays com numeros inteiros aleatórios
p = np.random.randint(50, 100, (3, 3))
print(p)

[[80 72 53]
 [50 79 81]
 [89 77 62]]


# Atributos

In [19]:
print(p.shape)    #Tupla de inteiros indicando o tamanho de cada dimensão.
print(p.ndim)     #Número de dimensões (eixos) do array.
print(p.size)     #Número total de elementos no array.
print(p.dtype)    #Tipo de dado dos elementos (ex: `int64`, `float64`, `bool`).
print(p.itemsize) #Tamanho em bytes de cada elemento.
print(p.nbytes)   #Tamanho total em bytes consumido pelo array.
print(p.T)        #A transposta do array (para arrays 2D+).

(3, 3)
2
9
int32
4
36
[[80 50 89]
 [72 79 77]
 [53 81 62]]


# Funções gerais

In [20]:
# Repetindo os elementos de um array
print(c)
print(np.repeat(c, 3))
print(np.tile(c, 3))

[[1 2 3 4]
 [5 6 7 8]]
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8]
[[1 2 3 4 1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8 5 6 7 8]]


### Indexação em Arrays NumPy

Todas as formas de acessar um elemento de uma lista funciona com o ndarray
mas podemos acessar de algumas outras forma

In [21]:
#Acessando indices específicos
q = [1, 2, 5, 6]
print(a)
print(a[q])

[1 2 3 4 5 6 7 8]
[2 3 6 7]


In [22]:
#acessando através de mascaras
r = (a % 2 == 0)
print(a)
print(r)
print(a[r])

[1 2 3 4 5 6 7 8]
[False  True False  True False  True False  True]
[2 4 6 8]


# Operações Matemáticas com arrays

In [23]:
#Menor elemento no array
print(c.min())

1


In [24]:
#Maior elemento no array
print(c.max())

8


In [25]:
#Média
print(np.mean(c))

4.5


In [26]:
#Mediama
np.median(c)

4.5

In [27]:
#Desvio padrão
print(np.std(c))

2.29128784747792


In [28]:
#Variância
print(np.var(c))

5.25


In [29]:
#Soma dos elementos
print(np.sum(c))

36


In [30]:
#Soma acumulativa
c.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [31]:
#Produto dos elementos
print(np.prod(c))

40320


In [32]:
#Produto acumulativo
print (c.cumprod())

[    1     2     6    24   120   720  5040 40320]


In [33]:
s = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
t = np.array([10, 11, 12,13,14,15,16,17,18]).reshape(3,3)
print(s)
print(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [34]:
# Soma dos arrays
u = np.add(s, t)  
print(u)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [35]:
#Soma de escalar
v = s + 1.56543
print(v)

[[ 2.56543  3.56543  4.56543]
 [ 5.56543  6.56543  7.56543]
 [ 8.56543  9.56543 10.56543]]


In [36]:
#Multiplicação de escalar
w = s *  1.56543
print(w)

[[ 1.56543  3.13086  4.69629]
 [ 6.26172  7.82715  9.39258]
 [10.95801 12.52344 14.08887]]


In [37]:
# Multiplicar as duas matrizes
x = s @ t
print(x)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [38]:
#Soma de matrizes
y = s + t
print(y)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [39]:
#Multiplicação de matrizes
z = s @ t
print(z)
aa = s * t
print(aa)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [45]:
#Matriz inversa
ab = inv(z)
print(ab)

[[-1.88964715e+13  3.77929431e+13 -1.88964715e+13]
 [ 3.77929431e+13 -7.55858862e+13  3.77929431e+13]
 [-1.88964715e+13  3.77929431e+13 -1.88964715e+13]]


In [41]:
print(det(aa))

-216.00000000000526


In [42]:
#Usando o método around
ac = np.around(w, decimals=3)
print(ac)

[[ 1.565  3.131  4.696]
 [ 6.262  7.827  9.393]
 [10.958 12.523 14.089]]


In [52]:
#Extraindo a raiz quadrada de cada elemento
ad = np.sqrt(c)
print(ad)

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [53]:
#calculando a exponencial 
ae = np.exp(c)
print(ae)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]


In [54]:
#calculando o logarítimo decimal
af = np.log(c)
print(af)

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]]


In [60]:
#Calculando as funções trigonométricas
ag = np.sin(e)
ah = np.cos(e)
ai = np.tan(e)
aj = np.arcsin(e)
ak = np.arccos(e)
al = np.arctan(e)
print(ag)
print(ah)
print(ai)
print(aj)
print(ak)
print(al)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 9.624e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 9.624e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 9.624e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
[[1.57079633 1.57079633 1.57079633]
 [1.57079633 1.57079633 1.57079633]
 [1.57079633 1.57079633 1.57079633]]
[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 9.624e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


In [62]:
#Trazendo os valorfes absolutos
am = np.abs(ab)
print(am)

[[1.88964715e+13 3.77929431e+13 1.88964715e+13]
 [3.77929431e+13 7.55858862e+13 3.77929431e+13]
 [1.88964715e+13 3.77929431e+13 1.88964715e+13]]


In [71]:
#Arredondando paracima ou para baixo
an = np.ceil(af)
ao = np.floor(af)
print(af)
print(an)
print(ao)

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]]
[[0. 1. 2. 2.]
 [2. 2. 2. 3.]]
[[0. 0. 1. 1.]
 [1. 1. 1. 2.]]


In [73]:
#Compara dois arrays  elemento a elemento e retorna um novo array contendo o maior/menor
#valor de cada par de elementos correspondentes.
ap = np.random.randint(50, 100, (3, 3))
aq = np.random.randint(50, 100, (3, 3))
ar = np.maximum(ap,aq)
at = np.minimum(ap,aq)
print(ap)
print(aq)
print(ar)
print(at)

[[84 96 88]
 [69 81 59]
 [87 88 76]]
[[64 90 66]
 [97 68 78]
 [92 87 53]]
[[84 96 88]
 [97 81 78]
 [92 88 76]]
[[64 90 66]
 [69 68 59]
 [87 87 53]]


# Comparando array

In [74]:
au = np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
av = np.array([0,2,5,3,3,5,7,9]).reshape(2,4)

In [76]:
# Comparação item a item
aw = au == av
print(aw)

[[False  True False False]
 [False False  True False]]


In [77]:
#Comparação global
print(np.array_equal(au, av))
print(np.array_equal(a, b))

False
True


In [78]:
# Criando cópia do array
aw = np.copy(c)
print(aw)

[[1 2 3 4]
 [5 6 7 8]]
